title: Agustina Pesce
subtitle: Phd Geopysics
email: pesce.agustina@gmail.com
# description: >- # this means to ignore newlines until "baseurl:"
# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
# baseurl: /blog-agus # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Social media links in footer
orcid_number: 0000-0002-5538-8845
twitter_username: jekyllrb
github_username:  aguspesce
linkedin_username: citations?hl=es&amp;user=G2BRVw8AAAAJ

# Build settings
# theme: minima
plugins:
  - jekyll-feed

# Includes & excludes
include: ['_pages']
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - vendor
keep_files:
  - CNAME
  - .nojekyll
  - .git

sass:
  sass_dir: /assets/css/_sass
  style: compressed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
